### ISSUE TITLE
图片看不到

### ISSUE THREAD

**Issue by LZH20001220** [wasamtc/simpleSTL#1]
作者总结的真好！但是笔记中的图片好像存在了本地，github上看不到图片

**Comment by wasamtc** [comment]
感谢提醒，失效图片已全部更新。

**Comment by wasamtc** [comment]
> 作者总结的真好！但是笔记中的图片好像存在了本地，github上看不到图片

感谢提醒，失效图片已全部更新。

**Comment by wasamtc** [comment]
无法显示图片：已解决
